**现在主流的调试方法有4种**  
```
1 print
2 pdb
3 ipython
4 IDE自带的调试方案
```  
**1 print调试**  
待调试程序 ```err.py```  
```python
  1 def div(a, b):
  2     return a / b
  3 def main(a=1, b=0):
  4     return div(a, b)
  5 
  6 if __name__ == '__main__':
  7     main()
```
运行程序```python err.py```:  
```python
Traceback (most recent call last):
  File "err.py", line 7, in <module>
    main()
  File "err.py", line 4, in main
    return div(a, b)
  File "err.py", line 2, in div
    return a / b
ZeroDivisionError: division by zero
```
可以看到错误信息，错误信息，除以0了。现在用print进行调试```err.py```：
```python
  1 def div(a, b):
  2     return a / b
  3 def main(a=1, b=0):
  4     print(a, b)
  5     return div(a, b)
  6 
  7 if __name__ == '__main__':
  8     main()
```
运行程序```python err.py```:
```python
1 0
Traceback (most recent call last):
  File "err.py", line 8, in <module>
    main()
  File "err.py", line 5, in main
    return div(a, b)
  File "err.py", line 2, in div
    return a / b
ZeroDivisionError: division by zero

```  
可以看到执行div()前的a，b的值，b=0了，所以会报错。print放在正确的地方很关键。  
**使用pdb**   
pdb是python标准库内置的模块。修改```err.py```文件：
```python
  1 def div(a, b):
  2     return a / b
  3 def main(a=1, b=0):
  4     return div(a, b)
  5     
  6 if __name__ == '__main__':
  7     main()
```
使用pdb的-m参数进行单步调试```(py35) angus@ubuntu:~$ python -m pdb err.py```
```python
(py35) angus@ubuntu:~$ python -m pdb err.py
> /home/angus/err.py(1)<module>()
-> def div(a, b):
(Pdb) help

Documented commands (type help <topic>):
========================================
EOF    c          d        h         list      q        rv       undisplay
a      cl         debug    help      ll        quit     s        unt      
alias  clear      disable  ignore    longlist  r        source   until    
args   commands   display  interact  n         restart  step     up       
b      condition  down     j         next      return   tbreak   w        
break  cont       enable   jump      p         retval   u        whatis   
bt     continue   exit     l         pp        run      unalias  where    

Miscellaneous help topics:
==========================
pdb  exec

(Pdb) 
```
可以看到进入pdb调试环境，可以用help列出所有支持的命令，
n 下一行，a 列出所有参数，list 当前行下的代码块，c 执行到发生错误的地方，等等  
**3 使用pdb.set_trace()**  
修改```err.py```文件,
```python
  1 import pdb
  2 def div(a, b):
  3     pdb.set_trace()
  4     return a / b
  5 def main(a=1, b=0):
  6     return div(a, b)
  7 
  8 if __name__ == '__main__':
  9     main()
```
运行```err.py```，可直接运行到出错的地方，
```
(py35) angus@ubuntu:~$ python err.py
> /home/angus/err.py(4)div()
-> return a / b
(Pdb) p a
1
(Pdb) p b
0
(Pdb) a
a = 1
b = 0
(Pdb) c
Traceback (most recent call last):
  File "err.py", line 9, in <module>
    main()
  File "err.py", line 6, in main
    return div(a, b)
  File "err.py", line 4, in div
    return a / b
ZeroDivisionError: division by zero
```
**4 使用IPython**  
修改```err.py```:
```python
  1 def div(a, b):
  2     return a / b
  3 def main(a=1, b=0):
  4     return div(a, b)
  5 
  6 if __name__ == '__main__':
  7     main()
```
运行```ipython -i err.py --pdb --no-banner```:  
```
~/err.py in main(a, b)
      2         return a / b
      3 def main(a=1, b=0):
----> 4         return div(a, b)
      5 
      6 if __name__ == '__main__':

~/err.py in div(a, b)
      1 def div(a, b):
----> 2         return a / b
      3 def main(a=1, b=0):
      4         return div(a, b)
      5 

ZeroDivisionError: division by zero
> /home/angus/err.py(2)div()
      1 def div(a, b):
----> 2         return a / b
      3 def main(a=1, b=0):
      4         return div(a, b)
      5 

ipdb> p b
0
```
程序运行在错误的地方就停止。

**经验总结**  
调试只是开发时的手段，线上环境应该记录业务日志，也应该是用sentry搜集错误日志，通过这些日志去回溯问题，不应该出了问题线上调试。  
